name=input("enter the name")
usn=input(int("Enter the USN"))
course=input("enter the course")
address=input("enter the address")
collage=input("enter the collage")
print("name",name)
print("usn",usn)
print("course",course)
print("address",address)
print("collage",collage)
